### ISSUE TITLE
Pins with integer attributes not supported?

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/seneca-amqp-transport#60]
If I define a seneca instance to listen to a message that contains an integer attribute I get a fatal error. The same message, with a string value instead will work.
This is unfortunate because messages like `remote:1` will get translated to `{remote:1}` and not `{remote:'1'}`

### Won't work:
```js
const Seneca = require('seneca')
const seneca = Seneca()
seneca.use('amqp-transport')
seneca.listen({
  type: 'amqp',
  url: 'amqp://guest:guest@localhost:5672',
  pin: 'remote:1'
})
```

```js
const Seneca = require('seneca')
const seneca = Seneca()
seneca.use('amqp-transport')
seneca.listen({
  type: 'amqp',
  url: 'amqp://guest:guest@localhost:5672',
  pin: {remote:1}
})
```

### Will work

```js
const Seneca = require('seneca')
const seneca = Seneca()
seneca.use('amqp-transport')
seneca.listen({
  type: 'amqp',
  url: 'amqp://guest:guest@localhost:5672',
  pin: {remote:'1'}
})
```

```js
const Seneca = require('seneca')
const seneca = Seneca()
seneca.use('amqp-transport')
seneca.client({
  type: 'amqp',
  url: 'amqp://guest:guest@localhost:5672',
  pin: 'remote:1'
})
```

## Error received

```
Seneca Fatal Error
==================

Message: seneca: value.replace is not a function

Code: transport_listen

Details: { type: 'amqp',
  url: 'amqp://guest:guest@localhost:5672',
  pin: 'remote:1',
  'orig$':
   { TypeError: value.replace is not a function
       at _.forOwn (/Users/paolochiodi/Projects/seneca/seneca-zipkin-tracer/node_modules/seneca-amqp-transport/lib/amqp-util.js:152:21)
       at /Users/paolochiodi/Projects/seneca/seneca-zipkin-tracer/node_modules/seneca-amqp-transport/node_modules/lodash/lodash.js:4917:15
       at baseForOwn (/Users/paolochiodi/Projects/seneca/seneca-zipkin-tracer/node_modules/seneca-amqp-transport/node_modules/lodash/lodash.js:2979:24)
       at Function.forOwn (/Users/paolochiodi/Projects/seneca/seneca-zipkin-tracer/node_modules/seneca-amqp-transport/node_modules/lodash/lodash.js:12926:24)
       at stringify (/Users/paolochiodi/Projects/seneca/seneca-zipkin-tracer/node_modules/seneca-amqp-transport/lib/amqp-util.js:147:5)
```

**Comment by nfantone** [comment]
@paolochiodi Never run into this before. Then again, I've never tried setting a pin to a `Number`. Looks like a bug.

Incidentally, is this even supported by Seneca, in general? Do other transports behave differently?

**Comment by paolochiodi** [comment]
@rjrodger or @mcdonnelldean may better know what is the intended behaviour, but from my experience it works with seneca. I've also tried both http and tcp transports and they work as expected
