### ISSUE TITLE
node 8 fails

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-amqp-transport#97]
> seneca-amqp-transport@2.1.0 test /home/travis/build/senecajs/seneca-core-plugins-next/seneca-amqp-transport
> gulp test
/home/travis/build/senecajs/seneca-core-plugins-next/seneca-amqp-transport/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^
TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/home/travis/build/senecajs/seneca-core-plugins-next/seneca-amqp-transport/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/home/travis/build/senecajs/seneca-core-plugins-next/seneca-amqp-transport/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/senecajs/seneca-core-plugins-next/seneca-amqp-transport/node_modules/gulp-release/lib/release.js:11:13)

**Comment by rjrodger** [comment]
The context is I'm trying to integrate into the core plugin validation suite: https://travis-ci.org/senecajs/seneca-core-plugins-next/jobs/250728008

**Comment by nfantone** [comment]
Hi @rjrodger. Though that _is_ last released version, the code you are running tests against is pretty old. `develop` does not require `gulp` anymore and works fine on latest `node` (Travis runs on 6 and 8). How are you pulling the versions out?

**Comment by nfantone** [comment]
@rjrodger Not sure if this helps you in any way, but I just published a new `2.2.0` tag to `npm`.

Also, bear in mind that running `npm test` on this repo requires a live RabbitMQ instance due to e2e tests being included. If you want to exclude them, you'll need to use `npm run test:unit`, instead.

**Comment by rjrodger** [comment]
Hi Nicolas - thanks :)
Nearly have it working - adding rabbitmq service to travis.

**Comment by rjrodger** [comment]
It works! https://travis-ci.org/senecajs/seneca-core-plugins-next

I'm standardising a few things to make plugin validation easier so releases are safer, to avoid:
https://gitter.im/senecajs/seneca?at=595b9e193230e14f3a239f9c
